version: '3.5'

services:
  bff-service-db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./scripts/local-postgres-setup:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  db-migration-dev:
    image: boxfuse/flyway:5.2.4
    command: -url=jdbc:postgresql://bff-service-db:5432/bff_service_local -schemas=core -user=postgres -password=postgres -connectRetries=60 migrate
    volumes:
      - ./db/migrations:/flyway/sql
    depends_on:
      - bff-service-db

  db-migration-test:
    image: boxfuse/flyway:5.2.4
    command: -url=jdbc:postgresql://bff-service-db:5432/bff_service_test -schemas=core -user=postgres -password=postgres -connectRetries=60 migrate
    volumes:
      - ./db/migrations:/flyway/sql
    depends_on:
      - bff-service-db