version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@1.8.4

jobs:
  run-tests:
    working_directory: ~/public_service
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Unit Test
          command: npm run test:unit
      - run:
          name: Code Coverage
          command: npm run coverage
      - run:
          name: Move Test Result
          command: mkdir -p test-results/mocha && cp test-results.xml test-results/mocha/results.xml
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results
  build-and-registry-container:
    working_directory: ~/public_service
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - setup_remote_docker
      - gcp-cli/install_and_initialize_cli
      - run: |
          IMAGE_AND_TAG=gcr.io/fin2you/public-service:$CIRCLE_SHA1
          docker build -t $IMAGE_AND_TAG .
          gcloud auth configure-docker
          docker push $IMAGE_AND_TAG

workflows:
  version: 2
  test-build-deploy:
    jobs:
      - run-tests
      - build-and-registry-container:
          requires:
            - run-tests